# This is a basic workflow to help you get started with Actions

name: Testing PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Run Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [macOS-latest]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: yarn install
        working-directory: ./makeuphara-front-end
        run: yarn install
      - name: yarn test
        working-directory: ./makeuphara-front-end
        run: yarn test
        env:
          CI: true
      - name: fail testing
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "테스트가 실패했습니다!",
              event: "COMMENT"
            })
        if: ${{ failure() && github.event_name == 'pull_request' }}
      - name: success testing
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "테스트를 통과했습니다!",
              event: "COMMENT"
            })
        if: ${{ success() && github.event_name == 'pull_request' }}
